packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

# 1 error occurred upgrading the following block:
# unhandled "clean_resource_name" call:
# there is no way to automatically upgrade the "clean_resource_name" call.
# Please manually upgrade to use custom validation rules, `replace(string, substring, replacement)` or `regex_replace(string, substring, replacement)`
# Visit https://packer.io/docs/templates/hcl_templates/variables#custom-validation-rules , https://www.packer.io/docs/templates/hcl_templates/functions/string/replace or https://www.packer.io/docs/templates/hcl_templates/functions/string/regex_replace for more infos.

source "amazon-ebs" "autogenerated_1" {
  ami_name      = "packer-example-{{ clean_resource_name `${timestamp()}` }}"
  instance_type = "t2.micro"
  region        = "us-east-2"
  source_ami    = "ami-0fb653ca2d3203ac1"
  ssh_username  = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    environment_vars = ["DEBIAN_FRONTEND=noninteractive"]
    inline           = ["sudo apt-get update", "sudo apt-get install -y php apache2", "sudo git clone https://github.com/brikis98/php-app.git /var/www/html/app"]
    pause_before     = "1m0s"
  }

}
